name: CI/CD

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

    workflow_dispatch:

jobs:
    lint-front:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - run: npm install && npm run lint:js >> $GITHUB_STEP_SUMMARY

    build-front:
        runs-on: ubuntu-latest
        needs:
            - lint-front
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - run: npm install && npm run build >> $GITHUB_STEP_SUMMARY